const allCourses = [
	{
		id: 1,
		title: "React.js - The Complete Guide",
		price: 100,
		instructor: "Ryan Dahl",
		duration: 50,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 2,
		title: "Node.js - The Complete Guide",
		price: 150,
		instructor: "Brad Traversy",
		duration: 30,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 3,
		title: "Python - The Complete Guide",
		price: 500,
		instructor: "Maximilian",
		duration: 20,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 4,
		title: "HTML - The Complete Guide",
		price: 50,
		instructor: "Stephen Grider",
		duration: 40,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 5,
		title: "CSS - The Complete Guide",
		price: 70,
		instructor: "Andrew Mead",
		duration: 10,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 6,
		title: "JavaScript - The Complete Guide",
		price: 400,
		instructor: "Schwarzmueller",
		duration: 35,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 7,
		title: "Django - The Complete Guide",
		price: 700,
		instructor: "Brian",
		duration: 45,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 8,
		title: "WordPress - The Complete Guide",
		price: 300,
		instructor: "Andrew ntje",
		duration: 55,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 9,
		title: "Bootstrap - The Complete Guide",
		price: 120,
		instructor: "Colt stele",
		duration: 17,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 10,
		title: "SQL - The Complete Guide",
		price: 500,
		instructor: "Ryan Cook",
		duration: 29,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 11,
		title: "MongoDB - The Complete Guide",
		price: 300,
		instructor: "Mongodb University",
		duration: 49,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 12,
		title: "AWS - The Complete Guide",
		price: 900,
		instructor: "AWS",
		duration: 70,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 13,
		title: "PHP - The Complete Guide",
		price: 230,
		instructor: "PHP academy",
		duration: 17,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 14,
		title: "Deno - The Complete Guide",
		price: 500,
		instructor: "Ryan Dahl",
		duration: 29,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
	{
		id: 15,
		title: "Vue.js - The Complete Guide",
		price: 200,
		instructor: "Laravel academy",
		duration: 47,
		image: "https://probella.com/wp-content/uploads/2018/03/React-JS.png",
	},
];

export default allCourses;
